export default [
  {
    id: '1',
    dob: new Date('2022-01-12'),
    sex: 'male',
    color: 'brown',
    breedQuality: 'normal',
    imgUrl: '/images/kin-browse/1.png',
  },
  {
    id: '2',
    dob: new Date('2022-02-10'),
    sex: 'female',
    color: 'white',
    breedQuality: 'premium',
    imgUrl: '/images/kin-browse/2.png',
  },
  {
    id: '3',
    dob: new Date('2021-12-12'),
    sex: 'male',
    color: 'black',
    breedQuality: 'premium',
    imgUrl: '/images/kin-browse/3.png',
  },
  {
    id: '4',
    dob: new Date('2022-01-13'),
    sex: 'female',
    color: 'white',
    breedQuality: 'champion',
    imgUrl: '/images/kin-browse/4.png',
  },
  {
    id: '5',
    dob: new Date('2022-02-01'),
    sex: 'female',
    color: 'white',
    breedQuality: 'champion',
    imgUrl: '/images/kin-browse/5.png',
  },
  {
    id: '6',
    dob: new Date('2022-01-10'),
    sex: 'male',
    color: 'white',
    breedQuality: 'champion',
    imgUrl: '/images/kin-browse/6.png',
  },
  {
    id: '7',
    dob: new Date('2022-01-19'),
    sex: 'male',
    color: 'white',
    breedQuality: 'normal',
    imgUrl: '/images/kin-browse/7.png',
  },
  {
    id: '8',
    dob: new Date('2022-01-09'),
    sex: 'male',
    color: 'brown',
    breedQuality: 'premium',
    imgUrl: '/images/kin-browse/8.png',
  },
  {
    id: '9',
    dob: new Date('2022-01-10'),
    sex: 'female',
    color: 'brown',
    breedQuality: 'champion',
    imgUrl: '/images/kin-browse/9.png',
  },
  {
    id: '10',
    dob: new Date('2022-01-20'),
    sex: 'male',
    color: 'brown',
    breedQuality: 'normal',
    imgUrl: '/images/kin-browse/10.png',
  },
  {
    id: '11',
    dob: new Date('2021-12-02'),
    sex: 'female',
    color: 'white',
    breedQuality: 'premium',
    imgUrl: '/images/kin-browse/11.png',
  },
  {
    id: '12',
    dob: new Date('2022-01-12'),
    sex: 'male',
    color: 'brown',
    breedQuality: 'normal',
    imgUrl: '/images/kin-browse/12.png',
  },
  {
    id: '13',
    dob: new Date('2022-01-12'),
    sex: 'male',
    color: 'brown',
    breedQuality: 'champion',
    imgUrl: '/images/kin-browse/13.png',
  },
  {
    id: '14',
    dob: new Date('2022-01-12'),
    sex: 'male',
    color: 'white',
    breedQuality: 'premium',
    imgUrl: '/images/kin-browse/14.png',
  },
  {
    id: '15',
    dob: new Date('2021-11-21'),
    sex: 'female',
    color: 'white',
    breedQuality: 'champion',
    imgUrl: '/images/kin-browse/15.png',
  },
  {
    id: '16',
    dob: new Date('2022-01-27'),
    sex: 'female',
    color: 'white',
    breedQuality: 'normal',
    imgUrl: '/images/kin-browse/16.png',
  },
  {
    id: '17',
    dob: new Date('2022-02-03'),
    sex: 'female',
    color: 'brown',
    breedQuality: 'normal',
    imgUrl: '/images/kin-browse/17.png',
  },
]
